// ============================================================
// DebatePage — Live debate room
// Split: left = visual table, right = argument feed
// ============================================================

import React, { useEffect, useRef } from "react";
import { useNavigate } from "react-router-dom";
import { useDebateStore } from "../store/debateStore.js";
import { PERSONAS } from "../store/personas.js";
import { useDebate } from "../hooks/useDebate.js";
import { DebateTable } from "../components/DebateTable.jsx";
import { ArgumentFeed } from "../components/ArgumentFeed.jsx";
import styles from "./DebatePage.module.css";

export function DebatePage() {
  const navigate = useNavigate();
  const store = useDebateStore();
  const { startDebate, stopDebate } = useDebate(PERSONAS);
  const hasStarted = useRef(false);

  const selectedPersonas = store.selectedPersonaIds.map(i => PERSONAS[i]);

  // Auto-start on mount
  useEffect(() => {
    if (!hasStarted.current && store.topic) {
      hasStarted.current = true;
      startDebate();
    } else if (!store.topic) {
      navigate("/");
    }
  }, []);

  const handleStop = () => {
    stopDebate();
  };

  const handleReset = () => {
    stopDebate();
    store.resetDebate();
    navigate("/");
  };

  const exportTranscript = () => {
    const lines = [
      "════════════════════════════════════════════════════════════",
      "   AI DEBATE SIMULATOR — TRANSCRIPT",
      "════════════════════════════════════════════════════════════",
      `   Topic:    ${store.topic}`,
      `   Date:     ${new Date().toLocaleString()}`,
      `   Debaters: ${selectedPersonas.map(p => `${p.name} (${p.ideology})`).join(", ")}`,
      "════════════════════════════════════════════════════════════",
      "",
      ...store.argumentHistory.map(h =>
        `[Turn ${h.turn}] ${h.personaName} — ${h.ideology}\n"${h.summary}"\n`
      ),
      "════════════════════════════════════════════════════════════",
      "   Generated by AI Debate Simulator",
      "════════════════════════════════════════════════════════════",
    ];
    const blob = new Blob([lines.join("\n")], { type: "text/plain" });
    const a = document.createElement("a");
    a.href = URL.createObjectURL(blob);
    a.download = `debate-${Date.now()}.txt`;
    a.click();
  };

  const progress = store.totalTurns > 0
    ? Math.min((store.currentTurn / store.totalTurns) * 100, 100)
    : 0;

  return (
    <div className={styles.page}>

      {/* ── Top Bar ────────────────────────────────────────── */}
      <header className={styles.topBar}>
        <div className={styles.topLeft}>
          <button className={styles.backBtn} onClick={handleReset} data-hover>
            ← BACK
          </button>
          <div className={styles.topicDisplay}>
            <span className={styles.topicLabel}>TOPIC</span>
            <span className={styles.topicText}>{store.topic}</span>
          </div>
        </div>

        <div className={styles.topRight}>
          <div className={styles.turnCounter}>
            <span style={{ color: "var(--white-mute)" }}>TURN</span>{" "}
            <span style={{ color: "var(--white-dim)" }}>{Math.min(store.currentTurn + 1, store.totalTurns)}</span>
            <span style={{ color: "var(--white-mute)" }}>/{store.totalTurns}</span>
          </div>

          {store.isRunning ? (
            <button className={styles.stopBtn} onClick={handleStop} data-hover>
              ⏹ STOP
            </button>
          ) : store.phase === "ended" ? (
            <button className={styles.exportBtn} onClick={exportTranscript} data-hover>
              ↓ EXPORT
            </button>
          ) : null}
        </div>
      </header>

      {/* ── Progress Bar ───────────────────────────────────── */}
      <div className={styles.progressTrack}>
        <div
          className={styles.progressFill}
          style={{
            width: `${progress}%`,
            background: store.currentSpeaker
              ? `linear-gradient(90deg, #1a1a1a, ${store.currentSpeaker.color})`
              : "linear-gradient(90deg, #2a2a2a, #888)",
          }}
        />
      </div>

      {/* ── Status Strip ───────────────────────────────────── */}
      <div className={styles.statusStrip}>
        <div className={styles.statusDot} data-active={store.isRunning} />
        <span className={styles.statusText}>
          {store.isLoading && store.currentSpeaker
            ? `${store.currentSpeaker.name} IS THINKING...`
            : store.currentSpeaker && !store.isLoading
            ? `${store.currentSpeaker.name} IS SPEAKING`
            : store.phase === "ended"
            ? `DEBATE CONCLUDED · ${store.argumentHistory.length} ARGUMENTS MADE`
            : store.isRunning
            ? "DEBATE IN PROGRESS"
            : "READY"}
        </span>
        {store.currentSpeaker && (
          <span className={styles.statusIdeology}>
            {store.currentSpeaker.ideology.toUpperCase()}
          </span>
        )}
      </div>

      {/* ── Body ───────────────────────────────────────────── */}
      <div className={styles.body}>

        {/* LEFT — Visual Table */}
        <div className={styles.leftPanel}>
          <DebateTable
            personas={selectedPersonas}
            currentSpeaker={store.currentSpeaker}
            isRunning={store.isRunning}
          />

          {/* Participant list */}
          <div className={styles.participants}>
            {selectedPersonas.map(p => (
              <div key={p.id} className={styles.participant}
                style={{ opacity: store.currentSpeaker?.id === p.id ? 1 : 0.3 }}>
                <div className={styles.participantDot} style={{ background: p.color }} />
                <span className={styles.participantName}
                  style={{ color: store.currentSpeaker?.id === p.id ? p.color : "#444" }}>
                  {p.name}
                </span>
              </div>
            ))}
          </div>

          {/* End CTA */}
          {store.phase === "ended" && (
            <div className={styles.endPanel}>
              <p className={styles.endText}>— DEBATE CONCLUDED —</p>
              <div className={styles.endBtns}>
                <button className={styles.endBtn} onClick={exportTranscript} data-hover>
                  EXPORT TRANSCRIPT
                </button>
                <button className={styles.endBtn} onClick={handleReset} data-hover>
                  NEW DEBATE
                </button>
              </div>
            </div>
          )}

          {store.error && (
            <div className={styles.errorBox}>{store.error}</div>
          )}
        </div>

        {/* RIGHT — Argument Feed */}
        <div className={styles.rightPanel}>
          <div className={styles.feedHeader}>
            <span className={styles.feedLabel}>ARGUMENT FEED</span>
            <span className={styles.feedCount}>{store.argumentHistory.length} ARGUMENTS</span>
          </div>
          <ArgumentFeed
            argumentHistory={store.argumentHistory}
            currentSpeaker={store.currentSpeaker}
            streamingText={store.streamingText}
            isLoading={store.isLoading}
          />
        </div>
      </div>
    </div>
  );
}
